swagger: '2.0'
info:
  description: >-
    zxy api      Swagger at [http://swagger.io](http://swagger.io) or on
    [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample,
    you can use the api key `special-key` to test the authorization     filters.
  version: 1.0.0
  title: Swagger zxy
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:8080'
basePath: /v1
tags:
  - name: teacher
    description: Operations about teacher
    externalDocs:
      description: Find out more about zxy
      url: 'http://swagger.io'
  - name: teaching
    description: 教学
  - name: parent
    description: 家长反馈
  - name: parentFeedback
    description: 家长反馈
  - name: uploadFile
    description: 上传文件
schemes:
  - http
paths:
  /teacher/students:
    get:
      tags:
        - teacher
      summary: 老师管理的学生列表和教学计划
      description: ''
      operationId: getTeacherStudents
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Student'
        '400':
          description: Invalid token supplied
      security:
        - teacher_token: []
  /teaching/plan/findByStudentId:
    get:
      tags:
        - teacher
      summary: 单个学生教学计划
      description: ''
      operationId: getTeachingPlanByStudentId
      produces:
        - application/json
      parameters:
        - name: studentId
          in: query
          description: studentId that need to be considered for filter
          required: true
          type: string
          collectionFormat: multi
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/TeachingPlan'
        '400':
          description: Invalid token supplied
      security:
        - teacher_token: []
  /teaching/plan:
    post:
      tags:
        - teaching
      summary: 创建教学计划
      description: 创建第一个教学阶段时，同时生成一个教学计划
      operationId: createTeachingPlan
      produces:
        - application/json
      parameters:
        - in: body
          name: teachingStep
          description: 第一个教学阶段
          required: true
          schema:
            $ref: '#/definitions/TeachingStep'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/TeachingPlan'
        '400':
          description: Invalid TeachingPlan
      security:
        - teacher_token: []
  /teaching/plan/step/:
    post:
      tags:
        - teaching
      summary: 创建教学阶段
      description: 创建教学阶段
      operationId: createTeachingStep
      produces:
        - application/json
      parameters:
        - name: teachingStep
          in: body
          description: 教学阶段数据
          required: true
          schema:
            $ref: '#/definitions/TeachingStep'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/TeachingStep'
        '400':
          description: Invalid TeachingPlan
      security:
        - teacher_token: []
  '/teaching/plan/step/{stepId}':
    delete:
      tags:
        - teaching
      summary: 删除教学阶段
      description: 只有老师能删除
      operationId: deleteTeachingStep
      produces:
        - application/json
      parameters:
        - name: stepId
          in: path
          description: The step that needs to be deleted
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid stepId supplied
        '404':
          description: stepId not found
      security:
        - teacher_token: []
  /teaching/plan/step/status:
    post:
      tags:
        - teaching
      summary: 创建教学动态
      description: ''
      operationId: createTeachingStatus
      produces:
        - application/json
      parameters:
        - name: teachingStatus
          in: body
          description: 教学动态数据
          required: true
          schema:
            $ref: '#/definitions/TeachingStatus'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/TeachingStatus'
        '400':
          description: Invalid TeachingStatus
      security:
        - teacher_token: []
  /parentFeedback:
    post:
      tags:
        - parentFeedback
      summary: 添加家长反馈
      description: ''
      operationId: createParentFeedbacksByStatus
      produces:
        - application/json
      parameters:
        - name: parentFeedback
          in: body
          description: 家长反馈数据
          required: true
          schema:
            $ref: '#/definitions/ParentFeedback'
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            items:
              $ref: '#/definitions/ParentFeedback'
        '400':
          description: Invalid status value
      security:
        - teacher_token: []
    put:
      tags:
        - parentFeedback
      summary: '修改家长反馈,当前仅用于设置消息为已读'
      description: ''
      operationId: updateParentFeedbacks
      produces:
        - application/json
      parameters:
        - name: parentFeedback
          in: body
          description: 家长反馈数据
          required: true
          schema:
            $ref: '#/definitions/ParentFeedback'
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid status value
      security:
        - teacher_token: []
  /parentFeedback/findByParentIdAndTeacherReaded:
    get:
      tags:
        - parentFeedback
      summary: '查找家长反馈,如果传入是否家长已经读过状态，则以此过滤'
      description: ''
      operationId: findParentFeedbacksByParentIdAndTeacherReaded
      produces:
        - application/json
      parameters:
        - name: parentId
          in: query
          required: true
          type: integer
          format: int64
        - name: teacherReaded
          in: query
          description: 老师是否已经读过
          required: false
          type: boolean
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/ParentFeedback'
        '400':
          description: Invalid status value
      security:
        - teacher_token: []
  /parent/status/findUnreadCount:
    get:
      tags:
        - parent
      summary: 查找家长未读的教学动态数量
      description: ''
      operationId: findParentUnreadStatusCount
      produces:
        - application/json
      parameters:
        - name: studentId
          in: query
          description: 查询的目标学生
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: integer
        '400':
          description: Invalid TeachingStatus
      security:
        - parent_token: []
  '/parent/status/{statusId}/read':
    post:
      tags:
        - parent
      summary: 家长读教学动态
      description: ''
      operationId: parentReadStatus
      produces:
        - application/json
      parameters:
        - in: path
          name: statusId
          description: ID of status that needs to be updated
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid TeachingStatus
      security:
        - parent_token: []
  /uploadFile:
    post:
      tags:
        - uploadFile
      summary: 上传文件
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: file
          type: file
          description: The file to upload.
      responses:
        '200':
          description: 'successful operation,文件地址'
          schema:
            type: string
        '400':
          description: Invalid stepId supplied
        '404':
          description: stepId not found
      security:
        - teacher_token: []
  /uploadFiles:
    post:
      tags:
        - uploadFile
      summary: 上传多全文件
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: files
          type: file
          description: The file to upload.
      responses:
        '200':
          description: 'successful operation,文件地址'
          schema:
            type: array
            items:
              type: string
        '400':
          description: Invalid stepId supplied
        '404':
          description: stepId not found
      security:
        - teacher_token: []
securityDefinitions:
  teacher_token:
    type: apiKey
    name: teacher_token
    in: header
  parent_token:
    type: apiKey
    name: teacher_token
    in: header
definitions:
  ApiResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string
  Student:
    type: object
    description: 学生
    properties:
      studentId:
        type: string
      name:
        type: string
      gradeName:
        type: string
      classId:
        type: string
      teachingPlan:
        $ref: '#/definitions/TeachingStep'
    xml:
      name: Student
  TeachingPlan:
    type: object
    description: 教学计划
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      studentId:
        type: string
      creatorTeacherId:
        type: string
        description: 创建的老师的ID
      content:
        type: string
      createDate:
        type: string
        format: date-time
      teachingSteps:
        type: array
        items:
          $ref: '#/definitions/TeachingStep'
        xml:
          name: teachingSteps
          wrapped: true
    xml:
      name: TeachingPlan
  TeachingStep:
    type: object
    description: 教学阶段
    properties:
      id:
        type: integer
        format: int64
      teachingPlanId:
        type: integer
        format: int64
      studentId:
        type: string
      name:
        type: string
      creatorTeacherId:
        type: string
        description: 创建的老师的ID
      content:
        type: string
      createDate:
        type: string
        format: date-time
      teachingStatuses:
        type: array
        items:
          $ref: '#/definitions/TeachingStatus'
        xml:
          name: teachingStatuses
          wrapped: true
    xml:
      name: TeachingPlan
  TeachingStatus:
    type: object
    description: 教学动态
    properties:
      id:
        type: integer
        format: int64
      createDate:
        type: string
        format: date-time
      teachingStepId:
        description: 所属的教学阶段
        type: integer
        format: int64
      studentId:
        type: string
      creatorTeacherId:
        type: string
        description: 创建的老师的ID
      creatorTeacherName:
        type: string
        description: 创建的老师的ID
      parentReaded:
        type: boolean
        description: 家长是否已经读过
      dimensions:
        type: array
        items:
          $ref: '#/definitions/Dimension'
        xml:
          name: dimensions
          wrapped: true
      files:
        type: array
        description: 最多6个图片，3个语音
        items:
          $ref: '#/definitions/TeachingStatusFile'
      complete:
        type: boolean
        default: false
    xml:
      name: TeachingStatus
  Dimension:
    type: object
    description: 教学动态-评价维度：teaching status dimension
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      value:
        type: number
        format: float
  TeachingStatusFile:
    type: object
    description: 教学动态-文件
    properties:
      fileType:
        type: string
        description: IMAGE或者VOICE
      url:
        type: string
  ParentFeedback:
    type: object
    description: 家长反馈
    properties:
      id:
        type: integer
        format: int64
      parentId:
        type: integer
        format: int64
      content:
        type: string
      teacherReaded:
        type: boolean
        description: 老师是否已经读过了
      feedbackResult:
        type: string
        description: 结果(positive很赞，negative待改进)
        enum:
          - positive
          - negative
      feedbackTarget:
        type: string
        description: 反馈对像(plan教学计划，status教学动态)
        enum:
          - plan
          - status
      feedbackTargetId:
        type: integer
        format: int64
      createDate:
        type: string
        format: date-time
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
