swagger: '2.0'
info:
  description: >-
    zxy api      Swagger at [http://swagger.io](http://swagger.io) or on
    [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample,
    you can use the api key `special-key` to test the authorization     filters.
  version: 1.0.0
  title: Swagger Petstore
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: petstore.swagger.io
basePath: /v1
tags:
  - name: teacher
    description: Operations about teacher
    externalDocs:
      description: Find out more about zxy
      url: 'http://swagger.io'
  - name: teaching
    description: 教学
schemes:
  - http
paths:
  /teacher/students:
    get:
      tags:
        - teacher
      summary: 老师管理的学生列表
      description: ''
      operationId: ''
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Student'
        '400':
          description: Invalid token supplied
      security:
        - teacher_token: []
  /teaching/plan/findByStudentId:
    get:
      tags:
        - teacher
      summary: 单个学生教学计划列表
      description: ''
      operationId: ''
      produces:
        - application/json
      parameters:
        - name: studentId
          in: query
          description: studentId that need to be considered for filter
          required: true
          type: integer
          collectionFormat: multi
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Student'
        '400':
          description: Invalid token supplied
      security:
        - teacher_token: []
securityDefinitions:
  teacher_token:
    type: apiKey
    name: teacher_token
    in: header
definitions:
  Student:
    type: object
    description: 学生
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string
      phone:
        type: string
      userStatus:
        type: integer
        format: int32
        description: Student Status
    xml:
      name: Student
  TeachingPlan:
    type: object
    description: 教学计划
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      desc:
        type: string
      createDate:
        type: string
        format: date-time
      teachingSteps:
        type: array
        items:
          $ref: '#/definitions/TeachingStep'
        xml:
          name: teachingSteps
          wrapped: true
    xml:
      name: TeachingPlan
  TeachingStep:
    type: object
    description: 教学阶段
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      desc:
        type: string
      createDate:
        type: string
        format: date-time
      teachingStatuses:
        type: array
        items:
          $ref: '#/definitions/TeachingStatus'
        xml:
          name: teachingStatuses
          wrapped: true
    xml:
      name: TeachingPlan
  TeachingStatus:
    type: object
    description: 教学动态
    properties:
      id:
        type: integer
        format: int64
      dimensions:
        type: array
        items:
          $ref: '#/definitions/Dimension'
        xml:
          name: dimensions
          wrapped: true
      photoUrls:
        type: array
        description: 最多6个
        xml:
          name: photoUrls
          wrapped: true
        items:
          type: string
      voiceUrls:
        type: array
        description: 最多3个
        xml:
          name: voiceUrls
          wrapped: true
        items:
          type: string
      complete:
        type: boolean
        default: false
    xml:
      name: TeachingStatus
  Dimension:
    type: object
    description: 教学动态-评价维度：teaching status dimension
    properties:
      name:
        type: string
      value:
        type: number
        format: float
  ApiResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
